// This file include osu api v2 requests we need in dev

###

// @name Client Credentials Grant

// ReferenceLink: https://osu.ppy.sh/docs/index.html#client-credentials-grant

POST {{BASE_URL}}/oauth/token
Accept: application/json
Content-Type: application/x-www-form-urlencoded

// Fill in it for yourself
client_id={{client_id}}&client_secret={{client_secret}}&grant_type=client_credentials&scope=public

> {% // Will set global AuthorizationToken. So just run it once for oneday.
    client.log("accessToken: " + response.body.access_token);

    client.global.set("AuthorizationToken", response.body.access_token);
%}

>>! Response\ClientCredentialsGrant.json

###

// @name Get Beatmap

// ReferenceLink: https://osu.ppy.sh/docs/index.html#get-beatmap
// /beatmaps/{beatmap}

< {%
    request.variables.set("beatmap", "364990")
%}

// Set url parameter "beatmap"
// 364990: Scarlet Faith - 仲村芽衣子


GET {{BASE_API_URL}}/beatmaps/{{beatmap}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AuthorizationToken}}

>>! Response\Beatmap\GetBeatmap.json

###

// @name Get User Scores

// ReferenceLink: https://osu.ppy.sh/docs/index.html#get-user-scores
// /users/{user}/scores/{type}

< {%
    request.variables.set("user", "11350021")  // wanna accuracy
    request.variables.set("type", "best")
%}

GET {{BASE_API_URL}}/users/{{user}}/scores/{{type}}
    ?include_fails=0
#    &mode=
#    &limit=
#    &offset=
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AuthorizationToken}}

>>! Response\Users\GetUserScores.json

