import type { paths } from "@/def/schemas"; // generated by openapi-typescript
import Login from "@/pages/auth/login.vue";
import router from "@/router";
import { useGlobal } from "@/store/global";
import createClient, { type Middleware } from "openapi-fetch";
import { markRaw } from "vue";

const myMiddleware: Middleware = {
    async onRequest(req, options) {
        const accessToken = localStorage.getItem("accessToken")
        if (accessToken !== null) {
            // we don't expire the token, so we can always use it
            req.headers.set("Authorization", `Bearer ${accessToken}`);
        }
        return undefined; // return undefined to leave request unchanged
    },
    async onResponse(res, options) {
        const global = useGlobal()
        const data = await res.json()
        if (res.status === 400) {
            global.showNotification("error", data.message)
            if (res.headers.get("fastapi-users")) {
                localStorage.removeItem("accessToken");
                if (router.currentRoute.value.meta.requiresAuth) {
                    global.openDialog(markRaw(Login))
                }
            }
        }
        return undefined; // return undefined to leave response unchanged
    },
};

export const client = createClient<paths>({ baseUrl: import.meta.env.VITE_URL });
client.use(myMiddleware);