import type { components } from "./schemas"; // generated by openapi-typescript

export type User = components['schemas']['User']
export type Stage = components['schemas']['Stage']
export type Ruleset = components['schemas']['Ruleset'];
export type OsuTeamCombination = components['schemas']['OsuTeamCombination']
export type TeamUserLinkPublic = components['schemas']['TeamUserLinkPublic']