import type { paths, components } from "./schemas"; // generated by openapi-typescript

export type User = components['schemas']['User']
export type TeamWithMembers = components['schemas']['TeamWithMembers']
export type TeamUserLinkPublic = components['schemas']['TeamUserLinkPublic']